### PR TITLE
Makes image ready for usage with Docker-Compose

### PR DESCRIPTION
**Pull request by funkyfuture**
- added export of db-configuration before launching run.sh
- added a sample docker-compose.yml
- extended README.md

Signed-off-by: funkyfuture <funkyfuture@riseup.net>

### CODE REVIEW

**Comment by samos123** [comment]
Thanks for your pull requests

can you submit pull request as single commits(Squash commits)? Also please only make the changes required to implement the fix / feature.

**Comment by funkyfuture** [comment]
can you give me a hint how to squash commits?
concerning this particular PR: there are no extra changes.

however, meanwhile my local changes do change quiet a lot. i haven't pushed these yet. would you like to have a look to judge if the direction of development is interesting for you at all?

**Comment by samos123** [comment]
Squashing commits can be done like this: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

What I meant with only doing changes that are required is that this will make it easier for me to accept changes independent of each other. I prefer to have clean commits, so no commits like remove debug statement which you also introduced in your previous commit. So I prefer a single commit that describes what the change achieves and it should only contain code needed.

Regarding your development I really think you're doing some useful and interesting stuff, but I haven't had time to test it yet.

**Comment by funkyfuture** [comment]
thanks, i knew that article, but never tried because of the word of caution. Do you know an elegant way to push the rebased commit to the same remote branch where the squashed commits have already been pushed?

for now, i pushed to another branch an will create the PR from there.

meanwhile i did a lot of tweaking, and hope to get this feazed into meaningful branches.
i also noted some future features, shall i open Issues for these proposals?

**Comment by samos123** [comment]
Yea you can use git push -f origin your-branch:your-branch this would do a force push, overwriting previous commits in branch with your local branch changes which contain the squashed commits.

I also already merged one change(download build directly instead of git submodule) of you through a cherry-pick. So you don't have to create a pull request for that change anymore.

Yea if you're willing to open an issue for that first so we can discuss  that would be great. And again thanks a lot for willing to change your commits.

**Pull request closed without merging**
